[project]
name = "InsightaBackend"
version = "0.1.0"
description = "Insighta Backend with full features auth, rate limitiing, RBAC, natural language querying, etc."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cachetools>=7.1.1",
    "fastapi[all,standard]>=0.135.3",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.12.1",
    "sqlalchemy>=2.0.49",
    "uuid6>=2025.0.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [
"tests",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
